### ISSUE TITLE
Trouble running vncdesk for the first time

### ISSUE THREAD

**Issue by ghost** [feklee/vncdesk#11] opened 2017-03-16 14:35 UTC
I am trying to figure out how to use vncdesk but running into some problems. Here is my settings.ini file:

```
$ cat .vncdesk/2/settings.ini 
[desktop]
width = 3840
height = 2160

[window]
scale_factor = 2
smoothing = false
```

I'm not entirely sure what the significance of the `2` is, and I tried `1` also but that didn't help. This is the message I get:

```
$ vncdesk 2 eog
usage: vncpasswd [file]
Xvnc command line: Xvnc :2 -geometry 3840x2160 -rfbauth .passwd -rfbport 5902 -depth 16 -pn -localhost &

Xvnc Free Edition 4.1.1 - built Jul 31 2015 19:10:31
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Thu Mar 16 10:30:14 2017
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5902
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/share/fonts/X11/Speedo/, removing from list!
Could not init font path element /usr/share/fonts/X11/CID/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
AUDIT: Thu Mar 16 10:30:14 2017: 16276 Xvnc: client 1 rejected from local host
vncconfig not available
Cannot find executable startup script
```

Not sure why it says `vncconfig` is not available because it exists:

```
$ vncconfig
No VNC extension on display :0.0
```

I'm on Ubuntu 14.04 x64 and I have realvnc and tightvnc servers installed.

Any idea what is going on?

**Comment by feklee** [comment] 2017-03-16 14:45
See documentation. You need to have a startup script `startup` in `~/.vncdesk/2/`. Does adding this file solve the problem? If not, please reopen this issue.

**Comment by ghost** [comment] 2017-03-16 15:01
Thank you @feklee, not sure how to re-open the same issue, but unfortunately it is still not working:

```
$ ls -l .vncdesk/2/startup 
-rwxrwxr-x 1 bp bp 32  3月 16 10:57 .vncdesk/2/startup
$ cat .vncdesk/2/startup
#!/bin/bash

exec xterm
```

```
$ vncdesk 2
usage: vncpasswd [file]
Xvnc command line: Xvnc :2 -geometry 3840x2160 -rfbauth .passwd -rfbport 5902 -depth 16 -pn -localhost &

Xvnc Free Edition 4.1.1 - built Jul 31 2015 19:10:31
Copyright (C) 2002-2005 RealVNC Ltd.
See http://www.realvnc.com for information on VNC.
Underlying X server release 40300000, The XFree86 Project, Inc


Thu Mar 16 10:57:58 2017
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on port 5902
 vncext:      created VNC server for screen 0
error opening security policy file /etc/X11/xserver/SecurityPolicy
Could not init font path element /usr/share/fonts/X11/Speedo/, removing from list!
Could not init font path element /usr/share/fonts/X11/CID/, removing from list!
Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
AUDIT: Thu Mar 16 10:57:58 2017: 23946 Xvnc: client 1 rejected from local host
vncconfig not available
AUDIT: Thu Mar 16 10:57:58 2017: 23946 Xvnc: client 1 rejected from local host
No protocol specified
xterm: Xt error: Can't open display: :2

(vncdesk:23937): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2769:41: Expected a valid selector
Disconnected from server
```

**Comment by ghost** [comment] 2017-03-16 15:17
I replaced vncpasswd with tightvncpasswd and Xvnc with Xtightvnc in the code and that seems to fix the issue.

**Comment by feklee** [comment] 2017-03-16 17:06
I just checked in an Ubuntu 14.04 installation with TightVNC, and I cannot replicate the issue.

That `vncconfig` is not available is a bogus error message, which I changed now. Very likely, `vncconfig` simply doesn't run with the parameters provided internally by vncdesk.

Most likely your installation of RealVNC caused the issue. *Where from did you get RealVNC?*

**Closed as completed by feklee** 2017-03-16 17:06 UTC

**Comment by ghost** [comment] 2017-03-16 17:39
I got it from the vnc4server package in universe.

**Comment by feklee** [comment] 2017-03-19 16:34
@bparker06 I was able to replicate the issue. The problem is with password generation, and I am currently investigating an alternative way to generate the password. If you're interested, see my pyDes issue: [Create encrypted passwords for VNC?][1]

[1]: https://github.com/toddw-as/pyDes/issues/2

**Comment by feklee** [comment] 2017-04-08 21:00
@bparker06 I'm happy to announce that version 1.7.0 supports RealVNC on Ubuntu 14.04.
